if(EXISTS "/home/szzz/bustub-2023spring/build_rel/test/deadlock_detection_test[1]_tests.cmake")
  include("/home/szzz/bustub-2023spring/build_rel/test/deadlock_detection_test[1]_tests.cmake")
else()
  add_test(deadlock_detection_test_NOT_BUILT deadlock_detection_test_NOT_BUILT)
endif()
