if(EXISTS "/home/szzz/bustub/build_rel/test/lock_manager_test[1]_tests.cmake")
  include("/home/szzz/bustub/build_rel/test/lock_manager_test[1]_tests.cmake")
else()
  add_test(lock_manager_test_NOT_BUILT lock_manager_test_NOT_BUILT)
endif()
