if(EXISTS "/home/szzz/bustub-2023spring/build_rel/test/trie_store_noncopy_test[1]_tests.cmake")
  include("/home/szzz/bustub-2023spring/build_rel/test/trie_store_noncopy_test[1]_tests.cmake")
else()
  add_test(trie_store_noncopy_test_NOT_BUILT trie_store_noncopy_test_NOT_BUILT)
endif()
